CREATE TABLE users (
		id INT PRIMARY KEY AUTO_INCREMENT,
		name VARCHAR(255) NOT NULL,
		email VARCHAR(255) NOT NULL,
		avatar VARCHAR(255),
		password VARCHAR(255) NOT NULL,
		last_name VARCHAR(255),
		location VARCHAR(255),
		role VARCHAR(50) NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE  jobs (
		id INT PRIMARY KEY AUTO_INCREMENT,
		user_id INT,
		company VARCHAR(255) NOT NULL,
		position VARCHAR(255) NOT NULL,
		status VARCHAR(50) NOT NULL,
		job_type VARCHAR(50) NOT NULL,
		job_location VARCHAR(255),
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		FOREIGN KEY (user_id) REFERENCES users(id)
	);